name: Test Calorimetro

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Scarica codice
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installa librerie
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Esegui Test
      run: |
        pytest -v test_main.py